version: "3.8"

services:
  cassandra1:
    image: cassandra:5.0
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9042:9042"
    networks:
      - cassandra_net
    environment:
      CASSANDRA_CLUSTER_NAME: DemoCluster
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: cassandra1
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M

  cassandra2:
    image: cassandra:5.0
    container_name: cassandra2
    hostname: cassandra2
    depends_on:
      - cassandra1
    networks:
      - cassandra_net
    environment:
      CASSANDRA_CLUSTER_NAME: DemoCluster
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: cassandra1
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M

  cassandra3:
    image: cassandra:5.0
    container_name: cassandra3
    hostname: cassandra3
    depends_on:
      - cassandra1
    networks:
      - cassandra_net
    environment:
      CASSANDRA_CLUSTER_NAME: DemoCluster
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_SEEDS: cassandra1
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M

networks:
  cassandra_net: